[build]
  command = "pnpm run build"
  publish = "packages/site/dist"
  functions = "packages/site/functions"

[dev]
  command = "pnpm --filter @my-pnpm-project/site dev"
  framework = "#custom"
  targetPort = 5173