[build]
  command = "pnpm run build"
  publish = "packages/site/dist"

[dev]
  command = "pnpm --filter @my-project/site dev"
  framework = "#custom"
  targetPort = 5173  # Matches Vite's default port